"""
Domain-level Pydantic schemas for the Egyptian Law Assistant.

These models define the data contracts at every bounded-context boundary.
LlamaIndex internal types (Document, NodeWithScore, Response) must NEVER
cross a boundary — they are always translated into one of these schemas first.

Rule: if a function signature in api/, evaluation/, or any other context
accepts or returns data from the pipeline, it uses these types.
"""

from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


class DocumentChunk(BaseModel):
    """
    Represents a single processed chunk stored in (or retrieved from) ChromaDB.

    Produced by: document_processing.ingestion_pipeline
    Consumed by: knowledge_base.indexer, query_engine.response_synthesizer,
                 api.routers.query (inside QueryResponse)
    """

    chunk_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for this chunk. Stable across re-ingestion of the same content.",
    )
    source_file: str = Field(
        description="Original filename (e.g., 'companies_law_159_1981.pdf')."
    )
    article_number: int | None = Field(
        default=None,
        description="Extracted article integer identifier (e.g., 73). None if not determinable.",
    )
    content: str = Field(
        description="The raw text content of this chunk.",
        min_length=1,
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Arbitrary key-value metadata from the source document. "
            "May include: law_name, law_number, publication_year, page_number, chunk_index."
        ),
    )

    @field_validator("source_file")
    @classmethod
    def source_file_must_not_be_empty(cls, v: str) -> str:
        """Prevent chunks with a blank source attribution."""
        if not v.strip():
            raise ValueError("source_file must not be blank.")
        return v.strip()

    @field_validator("content")
    @classmethod
    def content_must_not_be_whitespace_only(cls, v: str) -> str:
        """Reject chunks that contain only whitespace — these produce useless embeddings."""
        if not v.strip():
            raise ValueError(
                "content must contain at least one non-whitespace character. "
                "Whitespace-only chunks produce meaningless embeddings."
            )
        return v


class QueryRequest(BaseModel):
    """
    Inbound query from an API client.

    Validated by FastAPI before reaching the query pipeline.
    """

    query: str = Field(
        description="The natural language question in Arabic or English.",
        min_length=3,
        max_length=2000,
    )
    top_k: int = Field(
        default=10,
        ge=1,
        le=20,
        description="Number of document chunks to retrieve. Capped at 20 to control context window size.",
    )
    filters: dict[str, str] | None = Field(
        default=None,
        description=(
            "Optional ChromaDB metadata filters. "
            "Example: {'law_number': '159', 'publication_year': '1981'}"
        ),
    )

    @field_validator("query")
    @classmethod
    def query_must_not_be_whitespace_only(cls, v: str) -> str:
        """Reject queries that are purely whitespace after stripping."""
        if not v.strip():
            raise ValueError("query must contain at least one non-whitespace character.")
        return v.strip()


class QueryResponse(BaseModel):
    """
    Outbound response returned by the query API.

    The answer is generated by the LLM; source_chunks provide citation
    evidence so callers can verify the answer against the source law.
    """

    answer: str = Field(
        description="LLM-generated answer to the query, grounded in retrieved chunks."
    )
    source_chunks: list[DocumentChunk] = Field(
        description="The document chunks used as context for this answer.",
        min_length=0,  # May be empty if answer is a graceful 'not found' response
    )
    confidence_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description=(
            "Optional Ragas faithfulness score for this response. "
            "Populated during evaluation runs; None in standard query flow."
        ),
    )
    llm_provider_used: str = Field(
        description="Identifier of the LLM provider that generated this answer (e.g., 'ollama', 'claude')."
    )


class IngestionResult(BaseModel):
    """
    Summary returned after a completed ingestion run.

    Used by the ingestion API endpoint and logged to MLflow as run metadata.
    """

    total_files_processed: int = Field(ge=0)
    total_chunks_created: int = Field(ge=0)
    total_files_skipped: int = Field(
        default=0,
        ge=0,
        description="Files skipped because their content hash already exists in the IngestionCache.",
    )
    failed_files: list[str] = Field(
        default_factory=list,
        description="Filenames that raised an IngestionError. Processing continues for remaining files.",
    )
    collection_name: str = Field(
        description="ChromaDB collection written to (config-hash namespaced)."
    )